"""add password reset token fields to users

Revision ID: 76c8f36568c8
Revises: 3a36f46891d0
Create Date: 2026-08-30 13:25:17.863579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c8f36568c8'
down_revision = '3a36f46891d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token_hash')

    # ### end Alembic commands ###
