"""initial models: users, watched_counties, risk_logs

Revision ID: 836c393735f5
Revises: 
Create Date: 2026-08-25 11:05:43.201423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836c393735f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('watched_counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'county_name', name='uq_user_county')
    )
    with op.batch_alter_table('watched_counties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watched_counties_user_id'), ['user_id'], unique=False)

    op.create_table('risk_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watched_county_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watched_county_id'], ['watched_counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_logs_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_logs_watched_county_id'), ['watched_county_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_logs_watched_county_id'))
        batch_op.drop_index(batch_op.f('ix_risk_logs_recorded_at'))

    op.drop_table('risk_logs')
    with op.batch_alter_table('watched_counties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watched_counties_user_id'))

    op.drop_table('watched_counties')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
